----- Telescope
require("telescope").setup()
map("n", "<leader><space>", ":Telescope git_files<CR>")
map("n", "<leader>fb", ":Telescope current_buffer_fuzzy_find<CR>")
map("n", "<leader>fB", ":Telescope buffers<CR>")
map("n", "<leader>ff", ":Telescope find_files<CR>")
map("n", "<leader>fg", ":Telescope live_grep<CR>")
map("n", "<leader>fG", ":Telescope grep_string<CR>")
map("n", "<leader>fo", ":Telescope file_browser<CR>")
map("n", "<leader>ft", ":Telescope builtin<CR>")
